### ISSUE TITLE
Pixdim from Characters

### ISSUE THREAD

**Issue by muschellij2** [jonclayden/RNifti#12]
``` r
library(RNifti)
pixdim("hey")
#> [1] 1
```

I've added a simple call to `niftiHeader` in https://github.com/jonclayden/RNifti/pull/11 to try to address this.

Created on 2018-10-17 by the [reprex
package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by jonclayden** [comment]
Thanks again for catching this. The commit above contains a slight variation on your suggested update to the code to fix it, with the side-effect that `niftiHeader` objects now also have `pixdim` and `pixunits` attributes. Cases where `niftiHeader` produces an error could probably allow the error to just propagate upwards, but I'm catching them and returning a default value for backwards compatibility, as you did. Please check that this works for you, as a 0.10.0 release is fairly imminent.
