### ISSUE TITLE
Rescaling done in retrieveNifti scl_slope

### ISSUE THREAD

**Issue by muschellij2** [jonclayden/RNifti#13]
## Description of the problem
It seems as though if you put a `nifti` object into `retrieveNifti` it will have different behavior with respect to scale/slope if you put in a filename.

### Reading in the data
As we see it's a binary mask:
``` r
library(RNifti)
library(neurobase)
#> Loading required package: oro.nifti
#> oro.nifti 0.9.11.1
#> 
#> Attaching package: 'oro.nifti'
#> The following object is masked from 'package:RNifti':
#> 
#>     origin
img = readnii("roi.nii.gz")
unique(c(img))
#> [1] 0 1
rimg = readNifti("roi.nii.gz")
unique(c(rimg))
#> [1] 0 1
sum(img)
#> [1] 29437
sum(rimg)
#> [1] 29437
sum(as.array(retrieveNifti(rimg)))
#> [1] 29437
```

When we use `retrieveNifti` and then run `as.array` to calculate the sum, we get very different answers:
``` r
retrieveNifti("roi.nii.gz")
#> Internal image: "NIfTI image"
#> - 512 x 512 x 33 voxels
#> - 0.4883 x 0.4883 x 5 mm per voxel

sum(as.array(retrieveNifti("roi.nii.gz")))
#> [1] 29437
sum(as.array(retrieveNifti(img)))
#> [1] -8858340611
```

We see this is due to `scl_slope` and `scl_inter`:
``` r
dumpNifti(img)
#> NIfTI-1 header
#>     sizeof_hdr: 348
#>       dim_info: 0
#>            dim: 3  512  512  33  1  1  1  1
#>      intent_p1: 0
#>      intent_p2: 0
#>      intent_p3: 0
#>    intent_code: 0
#>       datatype: 8
#>         bitpix: 32
#>    slice_start: 0
#>         pixdim: -1.000000  0.488281  0.488281  5.000000  1.000000  1.000000  1.000000  1.000000
#>     vox_offset: 352
#>      scl_slope: 1
#>      scl_inter: -1024
#>      slice_end: 0
#>     slice_code: 0
#>     xyzt_units: 10
#>        cal_max: 1
#>        cal_min: 0
#> slice_duration: 0
#>        toffset: 0
#>        descrip: Time=154424.000
#>       aux_file: AXIAL_5MM
#>     qform_code: 1
#>     sform_code: 1
#>      quatern_b: 0.7071068
#>      quatern_c: 0.7071068
#>      quatern_d: 0
#>      qoffset_x: -218.7221
#>      qoffset_y: -161.1053
#>      qoffset_z: 8.700012
#>         srow_x: 0.000000  0.488281  0.000000  -218.722122
#>         srow_y: 0.488281  0.000000  0.000000  -161.105270
#>         srow_z: 0.000000  0.000000  5.000000  8.700012
#>    intent_name: 
#>          magic: n+1
```

After retrieving the info, it's scaled and sloped:
```r
aimg = retrieveNifti(img)
unique(c(as.array(aimg)))
#> [1] -1024 -1023
hist(as.array(aimg))
```

Histogram of the output array:
![](https://i.imgur.com/nwp89Sw.png)

But this information is also in the `.nii.gz`:
``` r

hd = dumpNifti("roi.nii.gz")
hd$scl_slope
#> [1] 1
hd$scl_inter
#> [1] -1024

img_hd = dumpNifti(img)
img_hd$scl_slope
#> [1] 1
img_hd$scl_inter
#> [1] -1024
```

I guess the fact that the data stored in the `.nii.gz` may actually have values which are not scaled already makes sense, it may be because the data are already transformed but the header is preserved: https://github.com/muschellij2/oro.nifti/blob/5b685cb75c8994f7336530d66d968813e86089fc/R/readS4.R#L453

<sup>Created on 2019-04-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jonclayden** [comment]
Hmm, it looks like this sequence of operations may be leading to the scaling being applied twice to the data. Could you make the image file available so I can replicate this, please?

**Comment by muschellij2** [comment]
Totally forgot - meant to drop it
[roi.nii.gz](https://github.com/jonclayden/RNifti/files/3065013/roi.nii.gz)

**Comment by jonclayden** [comment]
Sorry for the delay in following up with this. You're right that `oro.nifti`'s behaviour of changing the data but not resetting the scale and slope is probably the cause. I wasn't aware of this (and it's a bit odd, since it makes interpretation of the data inconsistent with NIfTI conventions). Do you know if this is long-standing behaviour? Is it likely to be safe to reset these fields when I convert back to `nifti_image`?

**Comment by muschellij2** [comment]
Ahh, I think there are a few things going on here

So the rescaling has been around for a while with respect to changing the inherent data within the array:
https://github.com/muschellij2/oro.nifti/blob/9a6f84446732b8d5ef96ba7baec9cac592f29b72/R/readS4.R#L360

1. By default, `oro.nifti` rescales the array information within the image, but does not change the header information (probably inconsistent with NIfTI).  
2. `neurobase` function `readnii` uses `readNIfTI` but has some different defaults compared to `readNIfTI`:
https://github.com/muschellij2/neurobase/blob/42e64ec64bed040b42fa74dff5caf356f079da93/R/readNIfTI2.R#L48.  It does not automatically change the headers (inconsistent), but has the option to do so with `reset_slope` (consistent).
3.  `writeNIfTI` does not automatically change the header info: https://github.com/muschellij2/oro.nifti/blob/c84ab0060a0be83bcc4e84e9943398edd55855fa/R/writeS4.R#L216
4.  `writenii` from `neurobase` does not do any rescaling either: https://github.com/muschellij2/oro.nifti/blob/c84ab0060a0be83bcc4e84e9943398edd55855fa/R/writeS4.R#L216

So I can change the behavior of `readNIfTI` (and therefore `readnii`) or `readnii` only.  What are your thoughts? @bjw34032

**Comment by muschellij2** [comment]
I see this is a big problem and needs to be addressed by this simple code:

``` r
setwd("~/Downloads")
library(oro.nifti)
#> oro.nifti 0.9.11.1
img = readNIfTI("roi.nii.gz")
range(img)
#> [1] 0 1
writeNIfTI(img, "roi2")
img2 = readNIfTI("roi2.nii.gz")
range(img2)
#> [1] -1024 -1023
```

<sup>Created on 2019-04-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by muschellij2** [comment]
Sorry - to be clear, options are 
1) Don't rescale the data in the array (would break a lot of code) - not suggesting this
2) change behavior of reading in the data (setting `scl_slope =1 ` and `scl_inter = 0`) after rescaling (recommending this)
3) change behavior or writing the data where `writeNIfTI` so that it rescales the data again.  Not going to fix issue here, but will fix the reading data in, doing nothing, then writing out should give the same header.

**Comment by muschellij2** [comment]
This push now makes it consistent behavior.  I'd still like @bjw34032 to weigh in on this fix as `oro.nifti` is his package:

``` r
setwd("~/Downloads")
library(RNifti)
library(oro.nifti)
#> oro.nifti 0.10.0
#> 
#> Attaching package: 'oro.nifti'
#> The following object is masked from 'package:RNifti':
#> 
#>     origin
library(neurobase)
img = readNIfTI("roi.nii.gz")
range(img)
#> [1] 0 1
img@scl_inter
#> [1] 0
img@scl_slope
#> [1] 1
writeNIfTI(img, "roi2")
img2 = readNIfTI("roi2.nii.gz")
range(img2)
#> [1] 0 1
img2@scl_inter
#> [1] 0
img2@scl_slope
#> [1] 1


img = readnii("roi.nii.gz")
unique(c(img))
#> [1] 0 1
rimg = readNifti("roi.nii.gz")
unique(c(rimg))
#> [1] 0 1
sum(img)
#> [1] 29437
sum(rimg)
#> [1] 29437
sum(as.array(retrieveNifti(rimg)))
#> [1] 29437

retrieveNifti("roi.nii.gz")
#> Internal image: "NIfTI image"
#> - 512 x 512 x 33 voxels
#> - 0.4883 x 0.4883 x 5 mm per voxel
sum(as.array(retrieveNifti("roi.nii.gz")))
#> [1] 29437
sum(as.array(retrieveNifti(img)))
#> [1] 29437
```

<sup>Created on 2019-04-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by bjw34032** [comment]
John, hi.  Thanks for looking into this.  Yes... not exactly what one
wants...  Sorry 'bout that.

Where is the roi.nii.gz file coming from or how can I create it myself?  I
kinda prefer the third option you provided, but am willing to be swayed.

B

**Comment by jonclayden** [comment]
From my side this isn't a catastrophe, but `RNifti` needs to know what to do with `nifti` objects to get sensible results. At the moment it assumes that directly mapping the slots to the equivalent header fields will result in a valid NIfTI object with the right sense. Clearly that's not a safe assumption at the moment.

For `oro.nifti`, the read-write-read loop should obviously result in consistent data values, and any of the options should achieve that. Options 1 and 2 require no change to `RNifti`, but mean it will do the wrong thing with objects from `oro.nifti` versions up to now. Option 3 leaves the in-memory object the same, so if I reset the slope and intercept on my side it should work with any version of `oro.nifti`. That might be more manageable, but either way is OK with me.

**Comment by jonclayden** [comment]
@bjw34032 The ROI file is linked in John’s second comment above.

**Comment by muschellij2** [comment]
OK - option 1 of no rescaling is out.
That leaves options 2 (change slope intercept - I'll call change header) and 3 (rescale back).  

## Rescaling back 
Advantages:

1. Rescaling back is the best from the viewpoint of reading data in, doing nothing, and then writing back should give you the "exact" same file (not exactly sure of if it will be from a binary file point of view).  That's the main advantage I see here, which can be important especially if you're going to other software to work with the NIfTI.
2. Data types.  You can save on storage with a large array by making array values integer but dividing/multiplying by some double/float in the slope.  

## Change header
Reasons I'd prefer change header are as follows:
1. The values of the array should be read in exactly the same in other software if you change the header to slope = 1, intercept = 0.
2. Many times we are copying the header over from array to array when creating new NIfTI objects.  The slope = 1, intercept = 0 works universally for all data types.
3. If you've copied the data over, and then are going to write the image out, you are going to rescale the data with the original slope/intercept parameters.  Not a problem if you're reading it back in (it will get rescaled), but 1) we need check to make sure slope != 0 and 2) values may look really strange if you bring into software that doesn't rescale.  This will also affect behavior from previous `oro.nifti` code I think a bit
4.  Breaking behavior on `RNifti` can be mitigated with `packageVersion("oro.nifti") <= SOME number` conditional

**Comment by jonclayden** [comment]
Yes, metadata reuse is an important point. If you apply some transformation to the data but leave the header as-is, and then try to "unscale" and round to integer to match the original file, you could be faced with a pretty dramatic loss of precision. You could check that the rounding is sane at write time, but that would add some overhead. So that does work in favour of resetting the slope and intercept on read.

Checking the `oro.nifti` package version is a reasonable mitigation but not a flawless one, as in principle one could be faced with a serialised object created by an earlier version than the one currently installed. I can live with that though, as a fairly unlikely edge case.

**Comment by muschellij2** [comment]
I agree.  I think most would use I/O to disk using NIfTI, but I agree, R
nifti objects stored from previous oro.nifti can definitely fail (as is
likely the case if caching is used in reproducible documents).

I'll wait for @bjw34032 to formally approve
https://github.com/muschellij2/oro.nifti/commit/19f9dcc227bca206c81b3a31b9b2e12db9ee35f4?w=1
then I will incorporate into the main.

**Comment by bjw34032** [comment]
@muschellij2 Approved!

**Comment by jonclayden** [comment]
For `RNifti`, the simplest solution is probably to just ignore the scale and intercept fields in all `nifti` objects. That leaves rescaling the data to `oro.nifti`, and I think will work with the old and new versions. Do either of you see any problem with that approach?

**Comment by muschellij2** [comment]
I think that works great.
John
