### ISSUE TITLE
Need path.expand for writeNifti.

### ISSUE THREAD

**Issue by muschellij2** [jonclayden/RNifti#2]
If you use a `~` in your path name, the path is not absolute and `writeNifti` fails:
```r
fname = system.file("extdata", "example.nii.gz", package = "RNifti")
image <- readNifti(fname)
writeNifti(image, file = "~/Desktop/test.nii.gz")
```
```
** ERROR (nifti_image_write_hdr_img2): cannot open output file '~/Desktop/test.nii.gz'
```

If you use `path.expand`, it works fine:
```r
writeNifti(image, file = path.expand("~/Desktop/test.nii.gz"))
```

**Comment by jonclayden** [comment]
Well spotted - thanks! `readNifti` passes its argument through `path.expand`, but `writeNifti` currently doesn't. I'll fix it. (The package has just been accepted to CRAN, though, so this will be for the next release.)
