### ISSUE TITLE
ERROR: compilation failed for package ‘RNifti’

### ISSUE THREAD

**Issue by casparms** [jonclayden/RNifti#26]
Hi! 
I am trying to install RNifti on a Linux system running R version 3.6.1. 
I am getting an error message "Makevars:6: *** missing separator.  Stop. ERROR: compilation failed for package ‘RNifti’" . 
Please see below. 
This happens with devtools, conda, and remotes. 
It happens with RScript and when I try it from within R. 
Any advice would be appreciated. 
Thanks! Caspar 

```
* installing *source* package ‘RNifti’ ...
** using staged installation
checking for gcc... x86_64-conda_cos6-linux-gnu-cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether x86_64-conda_cos6-linux-gnu-cc accepts -g... yes
checking for x86_64-conda_cos6-linux-gnu-cc option to enable C11 features... none needed
checking for library containing inflate... no
configure: creating ./config.status
config.status: creating src/Makevars
** libs
Makevars:6: *** missing separator.  Stop.
ERROR: compilation failed for package ‘RNifti’
* removing ‘/home/neuro_tools/R/RNifti’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpqT0FkL/file761418002c9b/RNifti_1.4.0.tar.gz’ had non-zero exit status
```

**Comment by jonclayden** [comment]
Thanks for picking this up. It's a formatting oversight that occurs on systems without a (findable) system `zlib`, which seems to be the case here. Could you try with the tip of the `master` branch, please, and confirm that it now works?

**Comment by casparms** [comment]
yes, it works now. thank you very much!

**Comment by jonclayden** [comment]
Great! I’ll get this wrapped up into a patch release and onto CRAN.

**Comment by jonclayden** [comment]
The new release has been accepted by CRAN and should be up shortly. Thanks for the report!
