### ISSUE TITLE
Exported niftiImage class?

### ISSUE THREAD

**Issue by muschellij2** [jonclayden/RNifti#3]
Do you plan on defining exporting the `niftiImage` class?  I was wondering because I've been trying to make generic functions and incorporate the RNifti package for these object types.

Currently, I can perform
```r
is.niftiImage = function(x) {
    inherits(x, "niftiImage")
}
myfunc(x) {
if (is.niftiImage(x)) {
#DEFINED FOR niftiImage 
} else {
}
```
but it would be useful to have
```r
setMethod("myfunc", "niftiImage", function() { #DEFINED FOR niftiImage 
})
```
but it does not seem that the `niftiImage` class is exported from RNifti.  This may be because I did not using LinkingTo, but don't know if that's the case.  

I don't know if I can implement this effectively or what you want.  If you plan on doing this, I'd appreciate it (disregard below).  Otherwise, I can take a shot with a PR (then see below)
It seems like I could send a PR with:

```r
setClass( "niftiImage", representation( pointer = "externalptr" ) )
```
but this seems to be an attribute versus element of the object.

**Comment by jonclayden** [comment]
Hi John. The `niftiImage` class is an S3 class, so you should be able to use it in S4 method signatures if you first call

    setOldClass("niftiImage")

That should register it within the S4 class hierarchy without requiring any modification to the `RNifti` package.
