### ISSUE TITLE
Undefined Symbols Error

### ISSUE THREAD

**Issue by Girish-Anadv-07** [jonclayden/RNifti#32]
1. I have cloned the repository and executed the make file inside it. 
2. I included `#include "RNifti.h"` in my code and used `RNifti::NiftiImage image("t1_c.nii.gz");` 
3. I executed the code using `g++ 3d_out.cpp -o  3d_out.out -L/opt/homebrew/lib -lafcpu -I/opt/homebrew/include -I./RNifti/standalone/`
4. I get errors 
ld: Undefined symbols:
  _nifti2_image_free, referenced from:
      RNifti::NiftiImage::release() in 3d_out-0eaa8b.o
  _nifti2_image_read, referenced from:
      RNifti::NiftiImage::NiftiImage(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool) in 3d_out-0eaa8b.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jonclayden** [comment]
Hi. Since you're using `g++` I'm going assume you're in a Unix-like environment, and I'm also assuming that the symlinks within the standalone directory (pointing to other parts of the repository) are in place.

With that said, it looks like you're not linking the `niftilib` files into your binary. The [example makefile](https://github.com/jonclayden/RNifti/blob/master/standalone/nii_info.make) has `znzlib/znzlib.o` and `niftilib/nifti1_io.o` (or `niftilib/nifti2_io.o`) as dependents, so they are included in the build. Does adding them help? For example,

```bash
g++ 3d_out.cpp RNifti/standalone/znzlib/znzlib.o RNifti/standalone/niftilib/nifti1_io.o -o  3d_out.out -L/opt/homebrew/lib -lafcpu -I/opt/homebrew/include -I./RNifti/standalone/
```

**Comment by Girish-Anadv-07** [comment]
(arrayfire) gm@Girishs-MacBook-Air hey % g++ 3d_out.cpp RNifti/standalone/znzlib/znzlib.o RNifti/standalone/niftilib/nifti1_io.o -o  3d_out.out -L/opt/homebrew/lib -lafcpu -I/opt/homebrew/include -I./RNifti/standalone/
ld: Undefined symbols:
  _gzclose, referenced from:
      _Xznzclose in znzlib.o
  _gzopen, referenced from:
      _znzopen in znzlib.o
  _gzputs, referenced from:
      _znzputs in znzlib.o
  _gzread, referenced from:
      _znzread in znzlib.o
  _gzseek, referenced from:
      _znzseek in znzlib.o
      _znzrewind in znzlib.o
  _gztell, referenced from:
      _znztell in znzlib.o
  _gzwrite, referenced from:
      _znzwrite in znzlib.o
  _nifti2_image_free, referenced from:
      RNifti::NiftiImage::release() in 3d_out-57c91c.o
  _nifti2_image_read, referenced from:
      RNifti::NiftiImage::NiftiImage(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool) in 3d_out-57c91c.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I get similar errors.

**Comment by Girish-Anadv-07** [comment]
Let me explain to you in detail on what I am doing:
1. git clone the repo
2. cd RNifti/standalone
3. make -f nii_info.make
4. Include the header file in the cpp code
5. Next Run `g++ 3d_out.cpp RNifti/standalone/znzlib/znzlib.o RNifti/standalone/niftilib/nifti1_io.o -o  3d_out.out -L/opt/homebrew/lib -lafcpu -I/opt/homebrew/include -I./RNifti/standalone/`

This is the only steps that I have followed. 

Let me know if there is a proper installation guide.

**Comment by jonclayden** [comment]
I assume you got to where you wanted on your own, since this is now closed.
