### ISSUE TITLE
interactive in shiny

### ISSUE THREAD

**Issue by rb643** [jonclayden/RNifti#34]
Wonderful package! Is there a way to:

1: Edit labels/colors of overlay images?
2. Plot this to a shiny dashboard while retaining the interactive bit. I'm now using this in my app to select and plot two images, then using the renderPlot() function to plot it, but that seems to remove the interactive option and fix it in place (while printing "right click to leave interactive mode" in the image without it actually being interaction.  
```
    dataset <- dataset[dataset$participant %in% input$data_select,]
    
    subject <- dataset$participant
    
    img <- readNifti(paste0("./data/nifti/",subject,".nii.gz"))
    img2 <- readNifti(paste0("./data/nifti/",subject,"_seg.nii.gz"))
        
    RNifti::view(img,img2,labels=T,interactive = T)
```

**Comment by jonclayden** [comment]
Hi Richard. Thanks for bringing this up. I don't actually know much about the nuts and bolts of how shiny's interactivity works, so I would need to look into that. Is it possible to share more of the code of the application, or a simple variant, so that I can try and replicate the issue?

**Comment by rb643** [comment]
Hi Jon, thanks for the quick response! My shiny app is rather convoluted with a fair amount amount of proprietary data at the moment so hard to quickly unpack as an example, but there is a similar deconstructed version here as well: https://github.com/muschellij2/neuroshiny/blob/master/app.R (though I can't get the click function to work in that example either), but the general shiny code should not be too dissimilar and instead of the entire `get_data()` function in that example I would ideally just be able to replace this with the RNifti::view function above.

**Comment by muschellij2** [comment]
I wouldn't recommend using that framework anymore.  i haven't been doing this for quite some time, but my recommendation is to use https://github.com/muschellij2/papayaWidget

**Comment by rb643** [comment]
Thanks John for the quick reply (and for merging two threads in one). With the papaya widget:
1. Do you have any guidance on how to embed that in an interactive shiny app? I.e., this doesn't work out of the box I think
```
display_nifti <- reactive({
    
    dataset <- dataset[dataset$participant %in% input$data_select,]
    
    subject <- dataset$participant
 
    papaya(c(paste0("./data/nifti/",subject,".nii.gz"), paste0("./data/nifti/",subject,"_seg.nii.gz")),
           options = list(papayaOptions(alpha = 0.5),
                          papayaOptions(alpha = 0.5, lut = "Red Overlay"))
    )
  })
  
  output$display_nifti <- renderPlot({
    display_nifti()
  })
```
2. Can you overlay multiple images with custom transparency and color settings this way (i.e., I actually want to overlap an atlas for example with 68 different colored regions but not sure what colormaps would be available)?

**Comment by muschellij2** [comment]
You need to use the shiny bindings, as demonstrated https://github.com/muschellij2/papayaWidget/blob/master/inst/examples/kirby21.R

**Comment by rb643** [comment]
Great! Hopefully final questions:
1. Can you customise the LUT colors beyond whats available from the drop-down menu?
2. Is there a way to scale the image to fit within a panel in my shiny app (I tried in vain to set height and width fixed as below, but it keeps filling the entire screen).

```
tabBox(
        id = "dash_2",
        width = NULL,
        height = 450,
        tabPanel(
          title = "MRI",
          withSpinner(
            papayaOutput("display_nifti"),
            type = 4,
            color = "#d33724",
            size = 0.7
          )
        )
)
```
and
```
display_nifti <- reactive({
    
    dataset <- dataset[dataset$participant %in% input$data_select,]
    
    subject <- dataset$participant
    
    papaya(c(paste0("./data/nifti/",subject,".nii.gz"), paste0("./data/nifti/",subject,"_seg.nii.gz")),
           height = 450, width = NULL,
           options = list(papayaOptions(alpha = 0.5),
                          papayaOptions(alpha = 0.5, lut = "Red Overlay"))
    )
    
  })
  
  output$display_nifti <- renderPapaya({
    display_nifti()
  })
```

**Comment by muschellij2** [comment]
You need to pass arguments to papayaOutput
Best,
John

**Comment by rb643** [comment]
even adding `papayaOutput("display_nifti", height = '450px', width = '100%'),` still makes it display over the entire page... (same when setting it to 25%).  Is it possible this somehow interacts with putting the entire in a div container or tab panel?

```
div(
      style = "position: relative; backgroundColor: #ecf0f5",
      tabBox(
        id = "dash_2",
        width = NULL,
        height = 450,
        tabPanel(
          title = "MRI",
          withSpinner(
            papayaOutput("display_nifti", height = '25%', width = '100%'),
            type = 4,
            color = "#d33724",
            size = 0.7
          )
        )
)))

```

**Comment by jonclayden** [comment]
@rb643 I'm not sure if one of these routes now does what you need, or you're still looking for a solution using `RNifti`? From a little experimentation I think the `view()` function would need some internal refactoring to make it work with Shiny, as the interaction model is different, and it doesn't seem to play well with the `layout()` function, which is used for the multi-panel layout.

**Comment by rb643** [comment]
Thanks Jon! Yes I think I got this working now with the papayviewer!
