### ISSUE TITLE
setting sform

### ISSUE THREAD

**Issue by martin3141** [jonclayden/RNifti#5]
Hi,

I noticed something that looks like a regression in version 0.7.0. The sform<- function doesn't seem to work as it does it version 0.6.0.

Martin

**Comment by jonclayden** [comment]
Hi Martin. Indeed, there has been a slight change to get the function, so that it follows R's usual semantics, but it should fundamentally work the same way. Can you expand on the issue or (preferably) give a code example that demonstrates it, please?

**Comment by martin3141** [comment]
Sure, the following works as expected in 0.6.0 but not in 0.7.0:

dummy_data <- RNifti::retrieveNifti(array(1, c(10,10,10)))
RNifti::\`sform<-\`(dummy_data, structure(matrix(1:16, nrow = 4), code = 2L))
xform(dummy_data)

the reason I'm not using:

sform(dummy_data) <- structure(matrix(1:16, nrow = 4), code = 2L)

is because I get the following note when doing a build check:

Missing or unexported object: ‘RNifti::sform’

Thanks for looking into this.

**Comment by jonclayden** [comment]
OK, I see. If you want to get this working without loading the `RNifti` package, you'll need to assign the result of your explicit call to `sform<-`, viz.

```r
dummy_data <- RNifti::retrieveNifti(array(1, c(10,10,10)))
dummy_data <- RNifti::`sform<-`(dummy_data, structure(matrix(1:16, nrow = 4), code = 2L))
RNifti::xform(dummy_data)
#      [,1] [,2] [,3] [,4]
# [1,]    1    5    9   13
# [2,]    2    6   10   14
# [3,]    3    7   11   15
# [4,]    4    8   12   16
```

This is because when you call infix `<-`, R implicitly creates a temporary variable and then returns it. The equivalent with `RNifti` loaded is

```r
library(RNifti)
dummy_data <- retrieveNifti(array(1, c(10,10,10)))
sform(dummy_data) <- structure(matrix(1:16, nrow = 4), code = 2L)
xform(dummy_data)
#      [,1] [,2] [,3] [,4]
# [1,]    1    5    9   13
# [2,]    2    6   10   14
# [3,]    3    7   11   15
# [4,]    4    8   12   16
```

which also works as it should. Does that help?

**Comment by martin3141** [comment]
Yes, that exactly what I needed, thanks!
