### ISSUE TITLE
Changing bitpix does nothing without datatype

### ISSUE THREAD

**Issue by muschellij2** [jonclayden/RNifti#8]
Examples rendered by https://github.com/tidyverse/reprex  @jennybryan 

``` r
library(RNifti)
path <- system.file("extdata", "example.nii.gz", package="RNifti")
nim = readNifti(path)
nim
#> Image array of mode "integer" (2.1 Mb)
#> - 96 x 96 x 60 voxels
#> - 2.5 x 2.5 x 2.5 mm per voxel
```
# Read example data

```r
hdr = dumpNifti(nim)
hdr
#> NIfTI-1 header
#>     sizeof_hdr: 348
#>       dim_info: 0
#>            dim: 3  96  96  60  1  1  1  1
#>      intent_p1: 0
#>      intent_p2: 0
#>      intent_p3: 0
#>    intent_code: 0
#>       datatype: 8
#>         bitpix: 32
#>    slice_start: 0
#>         pixdim: -1.0  2.5  2.5  2.5  0.0  0.0  0.0  0.0
#>     vox_offset: 352
#>      scl_slope: 0
#>      scl_inter: 0
#>      slice_end: 0
#>     slice_code: 0
#>     xyzt_units: 10
#>        cal_max: 2503
#>        cal_min: 0
#> slice_duration: 0
#>        toffset: 0
#>        descrip: TractoR NIfTI writer v3.0.0
#>       aux_file: 
#>     qform_code: 2
#>     sform_code: 2
#>      quatern_b: 0
#>      quatern_c: 1
#>      quatern_d: 0
#>      qoffset_x: 122.0339
#>      qoffset_y: -95.18523
#>      qoffset_z: -55.03814
#>         srow_x: -2.5000  0.0000  0.0000  122.0339
#>         srow_y: 0.00000  2.50000  0.00000  -95.18523
#>         srow_z: 0.00000  0.00000  2.50000  -55.03814
#>    intent_name: 
#>          magic: n+1
```

We see in the header:
```r
#>       datatype: 8
#>         bitpix: 32
```

# change bitpix only
```r
hdr$bitpix = 8
updateNifti(nim, template = hdr)
#> Image array of mode "integer" (2.1 Mb)
#> - 96 x 96 x 60 voxels
#> - 2.5 x 2.5 x 2.5 mm per voxel
dumpNifti(hdr)
#> NIfTI-1 header
#>     sizeof_hdr: 348
#>       dim_info: 0
#>            dim: 3  96  96  60  1  1  1  1
#>      intent_p1: 0
#>      intent_p2: 0
#>      intent_p3: 0
#>    intent_code: 0
#>       datatype: 8
#>         bitpix: 32
#>    slice_start: 0
#>         pixdim: -1.0  2.5  2.5  2.5  0.0  0.0  0.0  0.0
#>     vox_offset: 352
#>      scl_slope: 0
#>      scl_inter: 0
#>      slice_end: 0
#>     slice_code: 0
#>     xyzt_units: 10
#>        cal_max: 2503
#>        cal_min: 0
#> slice_duration: 0
#>        toffset: 0
#>        descrip: TractoR NIfTI writer v3.0.0
#>       aux_file: 
#>     qform_code: 2
#>     sform_code: 2
#>      quatern_b: 0
#>      quatern_c: 1
#>      quatern_d: 0
#>      qoffset_x: 122.0339
#>      qoffset_y: -95.18523
#>      qoffset_z: -55.03814
#>         srow_x: -2.5000  0.0000  0.0000  122.0339
#>         srow_y: 0.00000  2.50000  0.00000  -95.18523
#>         srow_z: 0.00000  0.00000  2.50000  -55.03814
#>    intent_name: 
#>          magic: n+1
```
No warning was issued about inconsistency in the bitpix/datatype designation and we see that nothing is changed in the image. 

# change datatype as well - works fine

```
hdr$datatype = 2
updateNifti(nim, template = hdr)
#> Image array of mode "integer" (2.1 Mb)
#> - 96 x 96 x 60 voxels
#> - 2.5 x 2.5 x 2.5 mm per voxel
dumpNifti(hdr)
#> NIfTI-1 header
#>     sizeof_hdr: 348
#>       dim_info: 0
#>            dim: 3  96  96  60  1  1  1  1
#>      intent_p1: 0
#>      intent_p2: 0
#>      intent_p3: 0
#>    intent_code: 0
#>       datatype: 2
#>         bitpix: 8
#>    slice_start: 0
#>         pixdim: -1.0  2.5  2.5  2.5  0.0  0.0  0.0  0.0
#>     vox_offset: 352
#>      scl_slope: 0
#>      scl_inter: 0
#>      slice_end: 0
#>     slice_code: 0
#>     xyzt_units: 10
#>        cal_max: 2503
#>        cal_min: 0
#> slice_duration: 0
#>        toffset: 0
#>        descrip: TractoR NIfTI writer v3.0.0
#>       aux_file: 
#>     qform_code: 2
#>     sform_code: 2
#>      quatern_b: 0
#>      quatern_c: 1
#>      quatern_d: 0
#>      qoffset_x: 122.0339
#>      qoffset_y: -95.18523
#>      qoffset_z: -55.03814
#>         srow_x: -2.5000  0.0000  0.0000  122.0339
#>         srow_y: 0.00000  2.50000  0.00000  -95.18523
#>         srow_z: 0.00000  0.00000  2.50000  -55.03814
#>    intent_name: 
#>          magic: n+1
```

# Changing datatype is the driver it seems

``` r
library(RNifti)
path <- system.file("extdata", "example.nii.gz", package="RNifti")
nim = readNifti(path)
hdr = dumpNifti(nim)
hdr$datatype = 2
updateNifti(nim, template = hdr)
#> Image array of mode "integer" (2.1 Mb)
#> - 96 x 96 x 60 voxels
#> - 2.5 x 2.5 x 2.5 mm per voxel
dumpNifti(hdr)
#> NIfTI-1 header
#>     sizeof_hdr: 348
#>       dim_info: 0
#>            dim: 3  96  96  60  1  1  1  1
#>      intent_p1: 0
#>      intent_p2: 0
#>      intent_p3: 0
#>    intent_code: 0
#>       datatype: 2
#>         bitpix: 8
#>    slice_start: 0
#>         pixdim: -1.0  2.5  2.5  2.5  0.0  0.0  0.0  0.0
#>     vox_offset: 352
#>      scl_slope: 0
#>      scl_inter: 0
#>      slice_end: 0
#>     slice_code: 0
#>     xyzt_units: 10
#>        cal_max: 2503
#>        cal_min: 0
#> slice_duration: 0
#>        toffset: 0
#>        descrip: TractoR NIfTI writer v3.0.0
#>       aux_file: 
#>     qform_code: 2
#>     sform_code: 2
#>      quatern_b: 0
#>      quatern_c: 1
#>      quatern_d: 0
#>      qoffset_x: 122.0339
#>      qoffset_y: -95.18523
#>      qoffset_z: -55.03814
#>         srow_x: -2.5000  0.0000  0.0000  122.0339
#>         srow_y: 0.00000  2.50000  0.00000  -95.18523
#>         srow_z: 0.00000  0.00000  2.50000  -55.03814
#>    intent_name: 
#>          magic: n+1
```

**Comment by jonclayden** [comment]
Hi John. The NIfTI-1 header structure is inherently redundant, and it's possible (as you've shown) to construct headers that are not self-consistent. Since having a value for `bitpix` that doesn't match `datatype` is illogical, I can't imagine a use-case where changing one without the other would be appropriate. The primacy of the `datatype` field is down to the niftilib C function `nifti_convert_nhdr2nim` (although it seems reasonable, since `bitpix` can be safely set from it, but not the reverse). `RNifti` could be tweaked to catch this particular inconsistency and produce a warning, but calling `updateNifti` with a list as the second argument is pretty advanced use, and if you need to do it a lot then perhaps a new accessor function is needed to make the operation safer...?

**Comment by muschellij2** [comment]
I guess my use case is that I have the data from multiple images, I
vectorize them to make a matrix for some matrix operations, then want to
convert back to an image.

Therefore reshape the image back to an array, then use updateNifti to
create a niftiImage object.  I guess you can use `writeNifti`, but what if
I want a niftiImage object?  It seems as though updateNifti is the only
way.  And if the template is of a different bitpix/datatype, there will be
some problems.

My use case is binary segmentations, running a combination (let's say
average), which produces probabilities between 0 and 1.  Then using the
template from one of these binary images may not result in a
continuous/float/double image.

John

**Comment by jonclayden** [comment]
OK, I see, but the datatype of the image is notional until you write it to a file. Up until that point, the array that R sees is either 32-bit integer or double-precision float (i.e., one or other of R's standard numeric datatypes). Is there a reason for wanting to carry more nuanced datatype information around while you're dealing with purely in-memory objects? I had envisioned `updateNifti` only being used for reducing object size for very large images, or for compatibility with other C/C++ code that wants to use the lower-level object (as with `RNiftyReg`).

**Comment by muschellij2** [comment]
May not be a problem then.  May have been from writeNIfTI in oro.nifti
where specification important, but was changed in neurobase::writenii.

I will try to find an example.  If not, you can close.

John

**Comment by muschellij2** [comment]
Still may be relevant to have a wrapper for taking an array (assuming same
orientation as as.array(original_image)) that are to be used for making a
niftiImage object.  I think updateNifti is still fine for this, but you may
see a different option as better.

John

**Comment by jonclayden** [comment]
OK, I could certainly add a `datatype` argument to `updateNifti`, to match `writeNifti`. I'll look into that when I have some time.

**Comment by jonclayden** [comment]
OK, I've added the argument, but there are some subtleties to this, so I would suggest not doing it lightly. Since `RNifti` can't keep an R array in sync with the internal `nifti_image` struct for arbitrary datatypes (since R only allows int32 and float64), `updateNifti(image,datatype=<whatever>)` will return an internal image, with only the C struct and no R array. That makes it very compact—and to be honest, saving memory seems like the main use case for this.

Along the way I fixed the issue that providing a partial metadata list as the second argument would not just update the fields specified, but replace everything else with defaults. Now, `updateNifti(image, list(intent_code=1000L))`, for example, should just set the intent code and leave everything else as it was.

**Comment by muschellij2** [comment]
Thanks - I think is very helpful for image manipulation on my end.

John

**Comment by muschellij2** [comment]
I am getting an error when trying to update using the new build:
```r
library(RNifti)
x = readNifti(system.file("extdata", "example.nii.gz", package="RNifti"))
hdr = dumpNifti(x)
hdr$cal_max = 100
res = updateNifti(x, template = hdr)
```

```
 *** caught segfault ***
address 0x0, cause 'memory not mapped'
```

**Comment by jonclayden** [comment]
Sorry, that was a pointer semantics bug. Should be fixed now.

Note also that `res = updateNifti(x, template = list(cal_max=100))` should work as a shorthand for this operation.
